### ISSUE TITLE
SSC-3: Weather type and temperature features

### ISSUE THREAD

**Issue by SammyVimes** [SammyVimes/storage_systems__classifier#3]
Добавляем тип погоды (дождь, ясно и т.п.) и температура в градусах цельсия

**Comment by SammyVimes** [comment]
Решено в https://github.com/SammyVimes/san_francisco_crimes/commit/63767f552785e0e8f53491fd8219f52cf75c6bd8

**Comment by JAkutenshi** [comment]
Мерж сделан, классификация на основе данных о погоде добавлена.
